Update readme.md
Installation on Mac OS X version 10.11.6 requires additional options to be able to install the required packages. I realised this after I got the following error message:

error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/greenlet': Operation not permitted.